// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: testdata/complex.proto

package testdata

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ComplextStatusPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ComplextStatusPb) Reset() {
	*x = ComplextStatusPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_complex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplextStatusPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplextStatusPb) ProtoMessage() {}

func (x *ComplextStatusPb) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_complex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplextStatusPb.ProtoReflect.Descriptor instead.
func (*ComplextStatusPb) Descriptor() ([]byte, []int) {
	return file_testdata_complex_proto_rawDescGZIP(), []int{0}
}

func (x *ComplextStatusPb) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ComplextStatusPb) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ComplexUserPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string            `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CurrentStatus *ComplextStatusPb `protobuf:"bytes,3,opt,name=currentStatus,proto3" json:"currentStatus,omitempty"`
}

func (x *ComplexUserPb) Reset() {
	*x = ComplexUserPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_complex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplexUserPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexUserPb) ProtoMessage() {}

func (x *ComplexUserPb) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_complex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexUserPb.ProtoReflect.Descriptor instead.
func (*ComplexUserPb) Descriptor() ([]byte, []int) {
	return file_testdata_complex_proto_rawDescGZIP(), []int{1}
}

func (x *ComplexUserPb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComplexUserPb) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ComplexUserPb) GetCurrentStatus() *ComplextStatusPb {
	if x != nil {
		return x.CurrentStatus
	}
	return nil
}

type ComplextPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category  uint32           `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"`
	Ips       []string         `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	Positions []uint32         `protobuf:"varint,3,rep,packed,name=positions,proto3" json:"positions,omitempty"`
	User      *ComplexUserPb   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Accounts  []*ComplexUserPb `protobuf:"bytes,5,rep,name=accounts,proto3" json:"accounts,omitempty"`
}

func (x *ComplextPb) Reset() {
	*x = ComplextPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_complex_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplextPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplextPb) ProtoMessage() {}

func (x *ComplextPb) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_complex_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplextPb.ProtoReflect.Descriptor instead.
func (*ComplextPb) Descriptor() ([]byte, []int) {
	return file_testdata_complex_proto_rawDescGZIP(), []int{2}
}

func (x *ComplextPb) GetCategory() uint32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *ComplextPb) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *ComplextPb) GetPositions() []uint32 {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *ComplextPb) GetUser() *ComplexUserPb {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ComplextPb) GetAccounts() []*ComplexUserPb {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_testdata_complex_proto protoreflect.FileDescriptor

var file_testdata_complex_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x3a, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x50, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x7b,
	0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x55, 0x73, 0x65, 0x72, 0x50, 0x62, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x40, 0x0a, 0x0d, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x78, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x62, 0x52, 0x0d, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x0a,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x74, 0x50, 0x62, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x55, 0x73, 0x65, 0x72, 0x50, 0x62, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x55, 0x73, 0x65, 0x72, 0x50, 0x62, 0x52, 0x08,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x6a, 0x73, 0x6f, 0x6e,
	0x70, 0x61, 0x63, 0x6b, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdata_complex_proto_rawDescOnce sync.Once
	file_testdata_complex_proto_rawDescData = file_testdata_complex_proto_rawDesc
)

func file_testdata_complex_proto_rawDescGZIP() []byte {
	file_testdata_complex_proto_rawDescOnce.Do(func() {
		file_testdata_complex_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_complex_proto_rawDescData)
	})
	return file_testdata_complex_proto_rawDescData
}

var file_testdata_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_testdata_complex_proto_goTypes = []interface{}{
	(*ComplextStatusPb)(nil), // 0: testdata.ComplextStatusPb
	(*ComplexUserPb)(nil),    // 1: testdata.ComplexUserPb
	(*ComplextPb)(nil),       // 2: testdata.ComplextPb
}
var file_testdata_complex_proto_depIdxs = []int32{
	0, // 0: testdata.ComplexUserPb.currentStatus:type_name -> testdata.ComplextStatusPb
	1, // 1: testdata.ComplextPb.user:type_name -> testdata.ComplexUserPb
	1, // 2: testdata.ComplextPb.accounts:type_name -> testdata.ComplexUserPb
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_testdata_complex_proto_init() }
func file_testdata_complex_proto_init() {
	if File_testdata_complex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_complex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplextStatusPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_complex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplexUserPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_complex_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplextPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_complex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_complex_proto_goTypes,
		DependencyIndexes: file_testdata_complex_proto_depIdxs,
		MessageInfos:      file_testdata_complex_proto_msgTypes,
	}.Build()
	File_testdata_complex_proto = out.File
	file_testdata_complex_proto_rawDesc = nil
	file_testdata_complex_proto_goTypes = nil
	file_testdata_complex_proto_depIdxs = nil
}
