// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: testdata/struct.proto

package testdata

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AddressPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    uint32 `protobuf:"varint,1,opt,name=area,proto3" json:"area,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AddressPb) Reset() {
	*x = AddressPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_struct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressPb) ProtoMessage() {}

func (x *AddressPb) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_struct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressPb.ProtoReflect.Descriptor instead.
func (*AddressPb) Descriptor() ([]byte, []int) {
	return file_testdata_struct_proto_rawDescGZIP(), []int{0}
}

func (x *AddressPb) GetArea() uint32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *AddressPb) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type MapInfoPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapName  string `protobuf:"bytes,1,opt,name=mapName,proto3" json:"mapName,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *MapInfoPb) Reset() {
	*x = MapInfoPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_struct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapInfoPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfoPb) ProtoMessage() {}

func (x *MapInfoPb) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_struct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfoPb.ProtoReflect.Descriptor instead.
func (*MapInfoPb) Descriptor() ([]byte, []int) {
	return file_testdata_struct_proto_rawDescGZIP(), []int{1}
}

func (x *MapInfoPb) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *MapInfoPb) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type PhoneNumberPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area   uint32 `protobuf:"varint,1,opt,name=area,proto3" json:"area,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PhoneNumberPb) Reset() {
	*x = PhoneNumberPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_struct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneNumberPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumberPb) ProtoMessage() {}

func (x *PhoneNumberPb) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_struct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumberPb.ProtoReflect.Descriptor instead.
func (*PhoneNumberPb) Descriptor() ([]byte, []int) {
	return file_testdata_struct_proto_rawDescGZIP(), []int{2}
}

func (x *PhoneNumberPb) GetArea() uint32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *PhoneNumberPb) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type TestStructPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex       uint32           `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Nicknames []string         `protobuf:"bytes,3,rep,name=nicknames,proto3" json:"nicknames,omitempty"`
	Maps      *MapInfoPb       `protobuf:"bytes,4,opt,name=maps,proto3" json:"maps,omitempty"`
	Phones    []*PhoneNumberPb `protobuf:"bytes,5,rep,name=phones,proto3" json:"phones,omitempty"`
	Address   *AddressPb       `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *TestStructPb) Reset() {
	*x = TestStructPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_struct_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestStructPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStructPb) ProtoMessage() {}

func (x *TestStructPb) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_struct_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStructPb.ProtoReflect.Descriptor instead.
func (*TestStructPb) Descriptor() ([]byte, []int) {
	return file_testdata_struct_proto_rawDescGZIP(), []int{3}
}

func (x *TestStructPb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestStructPb) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *TestStructPb) GetNicknames() []string {
	if x != nil {
		return x.Nicknames
	}
	return nil
}

func (x *TestStructPb) GetMaps() *MapInfoPb {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *TestStructPb) GetPhones() []*PhoneNumberPb {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *TestStructPb) GetAddress() *AddressPb {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_testdata_struct_proto protoreflect.FileDescriptor

var file_testdata_struct_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x39, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x62, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x61, 0x72,
	0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x09,
	0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x3b, 0x0a, 0x0d, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x62,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xdb, 0x01, 0x0a,
	0x0c, 0x54, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x50, 0x62, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x73, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x27, 0x0a, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x50, 0x62, 0x52, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x50, 0x62, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50,
	0x62, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x6a, 0x73,
	0x6f, 0x6e, 0x70, 0x61, 0x63, 0x6b, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdata_struct_proto_rawDescOnce sync.Once
	file_testdata_struct_proto_rawDescData = file_testdata_struct_proto_rawDesc
)

func file_testdata_struct_proto_rawDescGZIP() []byte {
	file_testdata_struct_proto_rawDescOnce.Do(func() {
		file_testdata_struct_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_struct_proto_rawDescData)
	})
	return file_testdata_struct_proto_rawDescData
}

var file_testdata_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testdata_struct_proto_goTypes = []interface{}{
	(*AddressPb)(nil),     // 0: testdata.AddressPb
	(*MapInfoPb)(nil),     // 1: testdata.MapInfoPb
	(*PhoneNumberPb)(nil), // 2: testdata.PhoneNumberPb
	(*TestStructPb)(nil),  // 3: testdata.TestStructPb
}
var file_testdata_struct_proto_depIdxs = []int32{
	1, // 0: testdata.TestStructPb.maps:type_name -> testdata.MapInfoPb
	2, // 1: testdata.TestStructPb.phones:type_name -> testdata.PhoneNumberPb
	0, // 2: testdata.TestStructPb.address:type_name -> testdata.AddressPb
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_testdata_struct_proto_init() }
func file_testdata_struct_proto_init() {
	if File_testdata_struct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_struct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_struct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapInfoPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_struct_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneNumberPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_struct_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestStructPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_struct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_struct_proto_goTypes,
		DependencyIndexes: file_testdata_struct_proto_depIdxs,
		MessageInfos:      file_testdata_struct_proto_msgTypes,
	}.Build()
	File_testdata_struct_proto = out.File
	file_testdata_struct_proto_rawDesc = nil
	file_testdata_struct_proto_goTypes = nil
	file_testdata_struct_proto_depIdxs = nil
}
